/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ConfigInput, JsonObject, JsonValue, PresetDocumentDto, RetryIntentDto, RunStatusDto, TeamConfig, TeamConfigDto, TeamOptionsDto, TeamStatusDto, TraceDetailDto, TraceSummaryDto } from '@rp-team/dsh-roleplay-team/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$72705465616d {
    applyStateEdit: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    cancel: (input: { conversationId: string; runId: string; }) => Promise<RemoteResult<RunStatusDto>>
    cancelTrial: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    compareTrial: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    copyPreset: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    deletePreset: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    deleteTrialScenario: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    discardRetry: (input: { conversationId: string; runId: string; requestId: string; }) => Promise<RemoteResult<{ discarded: boolean; }>>
    exportComponent: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    exportConfig: (input: { conversationId: string; }) => Promise<RemoteResult<PresetDocumentDto>>
    exportPreset: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    exportTrialScenario: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    freezeTrialSnapshot: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    getConfig: (input: { conversationId: string; }) => Promise<RemoteResult<TeamConfigDto>>
    getContextCatalog: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    getOptions: (input: { conversationId: string; }) => Promise<RemoteResult<TeamOptionsDto>>
    getPreset: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    getState: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    getStateEditStatus: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    getStatus: (input: { conversationId: string; }) => Promise<RemoteResult<TeamStatusDto>>
    getTrace: (input: { conversationId: string; runId: string; }) => Promise<RemoteResult<TraceDetailDto>>
    getTrial: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    getTrialScenario: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    getTrialTrajectory: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    importConfig: (input: { conversationId: string; preset: JsonValue; }) => Promise<RemoteResult<{ conversationId: string; config: TeamConfig; }>>
    importPreset: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    importTrialScenario: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    listPresets: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    listStateCheckpoints: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    listTraces: (input: { conversationId: string; }) => Promise<RemoteResult<TraceSummaryDto[]>>
    listTrials: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    listTrialScenarios: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    prepareComponentImport: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    previewConfig: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    previewParameters: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    restoreStateCheckpoint: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    retry: (input: { conversationId: string; runId: string; memberIds?: string[]; requestId: string; }) => Promise<RemoteResult<RetryIntentDto>>
    retryTrial: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    saveConfig: (input: ConfigInput) => Promise<RemoteResult<TeamConfigDto>>
    savePreset: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    saveTrialScenario: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    setManualAgents: (input: { conversationId: string; agentIds: string[]; }) => Promise<RemoteResult<{ conversationId: string; manualAgentIds: string[]; }>>
    startTrial: (input: JsonObject) => Promise<RemoteResult<JsonObject>>
  }
  interface TypertRemoteMap {
    'rpTeam/applyStateEdit': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/cancel': (input: { conversationId: string; runId: string; }) => Promise<RemoteResult<RunStatusDto>>
    'rpTeam/cancelTrial': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/compareTrial': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/copyPreset': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/deletePreset': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/deleteTrialScenario': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/discardRetry': (input: { conversationId: string; runId: string; requestId: string; }) => Promise<RemoteResult<{ discarded: boolean; }>>
    'rpTeam/exportComponent': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/exportConfig': (input: { conversationId: string; }) => Promise<RemoteResult<PresetDocumentDto>>
    'rpTeam/exportPreset': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/exportTrialScenario': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/freezeTrialSnapshot': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/getConfig': (input: { conversationId: string; }) => Promise<RemoteResult<TeamConfigDto>>
    'rpTeam/getContextCatalog': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/getOptions': (input: { conversationId: string; }) => Promise<RemoteResult<TeamOptionsDto>>
    'rpTeam/getPreset': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/getState': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/getStateEditStatus': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/getStatus': (input: { conversationId: string; }) => Promise<RemoteResult<TeamStatusDto>>
    'rpTeam/getTrace': (input: { conversationId: string; runId: string; }) => Promise<RemoteResult<TraceDetailDto>>
    'rpTeam/getTrial': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/getTrialScenario': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/getTrialTrajectory': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/importConfig': (input: { conversationId: string; preset: JsonValue; }) => Promise<RemoteResult<{ conversationId: string; config: TeamConfig; }>>
    'rpTeam/importPreset': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/importTrialScenario': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/listPresets': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/listStateCheckpoints': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/listTraces': (input: { conversationId: string; }) => Promise<RemoteResult<TraceSummaryDto[]>>
    'rpTeam/listTrials': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/listTrialScenarios': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/prepareComponentImport': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/previewConfig': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/previewParameters': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/restoreStateCheckpoint': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/retry': (input: { conversationId: string; runId: string; memberIds?: string[]; requestId: string; }) => Promise<RemoteResult<RetryIntentDto>>
    'rpTeam/retryTrial': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/saveConfig': (input: ConfigInput) => Promise<RemoteResult<TeamConfigDto>>
    'rpTeam/savePreset': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/saveTrialScenario': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
    'rpTeam/setManualAgents': (input: { conversationId: string; agentIds: string[]; }) => Promise<RemoteResult<{ conversationId: string; manualAgentIds: string[]; }>>
    'rpTeam/startTrial': (input: JsonObject) => Promise<RemoteResult<JsonObject>>
  }
  interface TypertRemoteNamespaceMap {
    'rpTeam': TypertRemoteNamespace$72705465616d
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
